"""Write scenario-local settings and a commented constraint catalogue.

The catalogue is generated from the constraint dataclasses so it reflects the
available constraint classes and fields.

    python scripts/make_scenario_config.py --all
    python scripts/make_scenario_config.py --scenario er

``write_scenario_config`` is used by the template workflow.  The command-line
interface only refreshes the catalogue block, leaving active settings alone.
"""

# Snakemake adds a preamble before this script, so a future import would be invalid.
import argparse
import dataclasses
import sys
import typing
from pathlib import Path
from collections.abc import Mapping

import yaml

sys.path.insert(0, str(Path(__file__).parent))

import constraints as C
from _helpers import ROOT, SCENARIO_CONFIG_NAME, available_scenarios, scenario_dir

BEGIN = "# ─── Available constraints (catalogue) ───"
END = "# ─── end catalogue ───"


class _IndentedDumper(yaml.SafeDumper):
    """Keep sequence entries visibly nested under their mapping key."""

    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)


def _deep_merge(base: Mapping, override: Mapping) -> dict:
    """Return a recursive merge where explicit scenario values win."""
    result = dict(base)
    for key, value in override.items():
        if isinstance(value, Mapping) and isinstance(result.get(key), Mapping):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def scenario_settings(
    template: Mapping, path: Path, workbook: Path, root: Path, *, merge: bool = False,
) -> dict:
    """Resolve the settings both members of a generated pair must share.

    On merge, active values in the existing scenario YAML override template
    defaults. The workbook is then rebuilt from those resolved settings, so
    workbook sheets and scenario years cannot diverge from their companion
    config. The destination name and workbook basename remain generator-owned.
    """
    base_path = root / "base_config.yaml"
    base = yaml.safe_load(base_path.read_text(encoding="utf-8")) or {}
    selected = {key: value for key, value in template.items() if key != "template"}
    effective = _deep_merge(base, selected)
    # These are workflow controls or derived locations, never scenario inputs.
    effective.pop("run", None)
    if path.exists() and merge:
        current = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(current, Mapping):
            raise ValueError(f"{path} must contain a YAML mapping to merge it safely.")
        effective = _deep_merge(effective, current)
    effective.pop("run", None)
    effective.setdefault("scenario", {})["name"] = str(template["scenario"]["name"])
    paths = dict(effective.get("paths", {}) or {})
    paths.pop("scenario_dir", None)
    paths["workbook"] = workbook.name
    effective["paths"] = paths
    return effective


def scenario_text(settings: Mapping) -> str:
    """A readable config with a usable constraints list and optional examples."""
    header = (
        "# Scenario-local settings generated by `snakemake generate_template`.\n"
        "# Edit active values for this scenario; repeat generation with\n"
        "# template.merge: true preserves those edits.\n"
        "# Template-only controls are kept in generate_template.yaml.\n\n"
    )
    active = dict(settings)
    # Keep this parent directly before the catalogue. With no policies it is a
    # valid null; removing '# ' from an example then turns it into this list.
    constraints = active.pop("constraints", None)
    active["constraints"] = constraints
    dumped = yaml.dump(
        active, Dumper=_IndentedDumper, sort_keys=False, allow_unicode=True,
    )
    if constraints is None or constraints == []:
        # An empty mapping value accepts a subsequently uncommented nested list;
        # explicit ``null``/``[]`` scalars emitted by PyYAML do not.
        dumped = dumped.replace("constraints: null\n", "constraints:\n", 1)
        dumped = dumped.replace("constraints: []\n", "constraints:\n", 1)
    return header + dumped + "\n" + catalogue() + "\n"


def write_scenario_config(
    template: Mapping, path: Path, *, workbook: Path, root: Path = ROOT,
    merge: bool = False, force: bool = False, check_only: bool = False,
    settings: Mapping | None = None,
) -> str:
    """Write one config beside its workbook, protecting an existing pair.

    Merge overlays an existing scenario YAML on the newly generated effective
    settings, so user values win while fresh defaults and the catalogue remain.
    Force saves the existing YAML as ``.bak`` before replacement.
    """
    if path.exists() and not (merge or force):
        raise ValueError(
            f"{path} already exists and has been preserved; enable template.merge "
            "or template.force to regenerate the scenario pair."
        )
    settings = dict(settings) if settings is not None else scenario_settings(
        template, path, workbook, root, merge=merge
    )
    if check_only:
        return "checked"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and force:
        backup = path.with_suffix(path.suffix + ".bak")
        backup.write_bytes(path.read_bytes())
    path.write_text(scenario_text(settings), encoding="utf-8")
    return "merged" if merge else "written"

#: A short purpose statement for each constraint class.
PURPOSE = {
    "CO2EmissionLimit": "Cap generation CO2 on the declared factor basis; workbook-built networks use electrical_output.",
    "FuelSupplyLimit": "Cap annual energy from one carrier — an absolute energy or fuel-supply ceiling.",
    "RPOConstraint": "Renewable purchase obligation: eligible generation >= share of served load.",
    "MonthlyCufsProfile": "Set monthly utilization ceilings or floors for one generator carrier.",
    "StoreCyclingLimit": "Limit Store discharge cycles per day/week/month/year; near-hourly sampling by default.",
    "ImportExportLimit": "Cap net flow on the corridor between two buses.",
    "TechnologyPhaseOut": "Cap a carrier's TOTAL capacity, on a per-year trajectory.",
    "ReserveMargin": "Firm capacity >= (1 + margin) x peak load, using capacity credits.",
}

#: Extra usage guidance for constraints with non-obvious fields.
NOTES = {
    "FuelSupplyLimit": (
        "The annual limit is fixed in MWh; additional capacity does not raise it.",
        "Use a separate named entry for each constrained carrier.",
        "With electrical_output, limit_mwh measures generated electrical energy.",
        "With fuel_input, dispatch is divided by Generator.efficiency before",
        "weighting, so limit_mwh measures input energy. This is an annual limit,",
        "not a separate seasonal or monthly budget.",
    ),
    "TechnologyPhaseOut": (
        "The ceiling includes existing generators and all active build vintages.",
        "Use a scalar for a constant ceiling or a map covering every model year.",
        "Year-map values are not interpolated. Fixed capacity above the ceiling",
        "is rejected because the constraint cannot retire fixed assets.",
    ),
    "ReserveMargin": (
        "Explicit capacity_credit_by_carrier values override profile-derived",
        "credits. Otherwise each generator's credit is its mean p_max_pu over",
        "the peak_hours highest-demand selected snapshots.",
        "Storage receives credit only when storage_peak_duration_h is set.",
        "Storage credit is limited by energy duration and connecting-Link power.",
        "Assets on one storage bus share a delivery channel; inspect its Links.",
        "Scope selects the demand and assets used in the calculation.",
        "Transmission capacity receives no independent credit.",
    ),
    "MonthlyCufsProfile": (
        "The monthly energy bound scales with generator capacity and hours.",
        "For an absolute annual MWh ceiling that does not grow with capacity,",
        "use FuelSupplyLimit. Neither class provides an absolute seasonal budget.",
    ),
    "StoreCyclingLimit": (
        "Each Store's discharge throughput is bounded by max_cycles times its",
        "energy capacity in each selected calendar window.",
        "With extendable storage, more energy capacity can relax this bound.",
        "With fixed storage, it directly limits discharge throughput.",
        "The default max_snapshot_hours is 1.0; coarse sampling is rejected",
        "unless that safeguard is explicitly changed. This does not constrain",
        "StorageUnits or set an absolute generator-energy budget.",
    ),
}

#: Fields shared by all constraint classes.
COMMON = {"name", "kind"}

#: Field example values. Class-specific entries take precedence over shared fields.
EXAMPLE = {
    "scope": "{bus: NR}   # optional — omit for the whole model; also state_id / region_id",
    "carrier": "Hydro",
    "eligible_carriers": "[Solar, Wind, Hydro]",
    "max_cf_by_month": "{1: 0.20, 2: 0.18, 6: 0.55}   # month -> capacity factor",
    "min_cf_by_month": "{6: 0.30}",
    "capacity_credit_by_carrier": "{Solar: 0.05, Wind: 0.10}",
    "basis": "electrical_output   # electrical_output | fuel_input",
    "math_symbol": '">="',
    "CO2EmissionLimit.limit_tco2": "12000000   # tCO2 per year",
    "FuelSupplyLimit.carrier": "Coal   # Coal | Lignite | Nuclear | Gas | Hydro | ...",
    "FuelSupplyLimit.limit_mwh": "90000000   # MWh per year",
    "ImportExportLimit.from_bus": "NR   # existing electricity bus",
    "ImportExportLimit.to_bus": "WR   # existing electricity bus",
    "ImportExportLimit.max_export_mw": "5000   # MW",
    "ImportExportLimit.max_import_mw": "5000   # MW",
    "TechnologyPhaseOut.carrier": "Coal",
    "TechnologyPhaseOut.max_capacity_mw": "250000   # MW; scalar applies in every modelled year",
    "StoreCyclingLimit.carrier": "Battery Storage",
    "StoreCyclingLimit.max_cycles": "1.0   # cycles per window",
    "StoreCyclingLimit.window": "daily              # daily | weekly | monthly | annual",
    "StoreCyclingLimit.max_snapshot_hours": "1.0   # refuse coarser sampling than this",
    "RPOConstraint.target_share": "0.43   # share of served load",
    "ReserveMargin.margin": "0.15",
    "ReserveMargin.peak_hours": "100   # average the credit over the N highest-demand hours",
    "ReserveMargin.storage_peak_duration_h": "4   # hours the peak event lasts; omit to leave storage uncredited",
}


def _type_name(annotation) -> str:
    text = str(annotation).replace("typing.", "").replace("<class '", "").replace("'>", "")
    return text.replace("ClassVar[", "").rstrip("]") if "ClassVar" in text else text


def catalogue() -> str:
    """The commented block, built from the dataclasses."""
    lines = [
        BEGIN,
        "#",
        "# Available constraints. Uncomment an entry, give it a",
        "# unique `name`, and it is applied. Numeric fields may be written as a",
        "# year-keyed map covering every modelled year and are resolved per horizon;",
        "# a bare number means the same value in every year.",
        "#",
        "# `scope` narrows a constraint that supports it and is optional there:",
        "# {bus: NR}, {state_id: KL} or {region_id: SR}. Omitted, the constraint",
        "# covers the whole model. ImportExportLimit uses its endpoints instead.",
        "#",
    ]
    for class_name, cls in sorted(C._CONSTRAINT_CLASSES.items()):
        lines.append(f"# {class_name}")
        lines.append(f"#   {PURPOSE.get(class_name, '')}")
        for note in NOTES.get(class_name, ()):
            lines.append(f"#   {note}".rstrip())
        lines.append("#")
        lines.append("#   - class: " + class_name)
        lines.append(f"#     name: my_{class_name.lower()}")
        for field in dataclasses.fields(cls):
            if field.name in COMMON:
                continue
            required = (
                field.default is dataclasses.MISSING
                and field.default_factory is dataclasses.MISSING  # type: ignore[misc]
            )
            if f"{class_name}.{field.name}" in EXAMPLE:
                value = EXAMPLE[f"{class_name}.{field.name}"]
            elif field.name in EXAMPLE:
                value = EXAMPLE[field.name]
            elif field.default is not dataclasses.MISSING and field.default is not None:
                value = repr(field.default)
            else:
                value = f"<{_type_name(field.type)}>"
            # the example may already carry its own trailing comment
            tag = "" if required or "#" in str(value) else "   # optional"
            lines.append(f"#     {field.name}: {value}{tag}")
        lines.append("#")
    lines.append(END)
    return "\n".join(lines)


def apply(path: Path) -> str:
    settings = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(settings, Mapping):
        raise ValueError(f"{path} must contain a YAML mapping.")
    path.write_text(scenario_text(settings), encoding="utf-8")
    return "refreshed"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario")
    parser.add_argument("--all", action="store_true")
    args = parser.parse_args()

    targets = available_scenarios() if args.all else [args.scenario]
    if not targets or targets == [None]:
        parser.error("pass --scenario NAME or --all")

    for scenario in targets:
        path = scenario_dir(scenario) / SCENARIO_CONFIG_NAME
        if not path.exists():
            print(f"  {scenario}: no {SCENARIO_CONFIG_NAME}, skipped")
            continue
        print(f"  {scenario}: catalogue {apply(path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
